### ISSUE TITLE
Failed to activate the redux package

### ISSUE THREAD

**Issue by gmcmenimen** [ShiningTrapez/atom-redux#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [redux](https://github.com/MortisEquilibrium/atom-redux) package 0.4.0

### Stack Trace
Cannot read property 'classList' of null

TypeError: Cannot read property 'classList' of null
    at Object.setCursorType (/Users/gregmcmenimen/.atom/packages/redux/lib/redux.coffee:214:57)
    at init (/Users/gregmcmenimen/.atom/packages/redux/lib/redux.coffee:225:9)
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/Users/gregmcmenimen/.atom/packages/redux/lib/redux.coffee:204:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36

Failed to activate the redux package

```
At Cannot read property 'classList' of null

TypeError: Cannot read property 'classList' of null
    at Object.setCursorType (/packages/redux/lib/redux.coffee:214:57)
    at init (/packages/redux/lib/redux.coffee:225:9)
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/packages/redux/lib/redux.coffee:204:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:24.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-nord-atom-syntax-accessibility-custom-comment-contrast)
     -0:06.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.4.0 
atom-alignment 0.13.0 
atom-beautify 0.30.4 
atom-typescript 11.0.6 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.10 
intentions 1.1.5 
jshint 1.8.6 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
pristine-ui 1.1.6 
protractor-atom-snippets 1.2.0 
pure-syntax 0.3.0 
react 0.16.2 
react-snippets 0.9.0 
redux 0.4.0 
todo-show 1.11.0 
```

**Comment by ShiningTrapez** [comment]
Thanks for the bug report but I'm no longer working on this, It was just a small project to dip my toe into Atom Plugin Development and to continue several packages I liked but had become incompatible with Atom DOM changes at the time. I now use Vim as my main editor so haven't really looked at this in some time; I've updated the Readme now to say as much. You could have a look at the original packages which should provides exactly the same functionality. 

- [Neon Cursor](https://github.com/muchweb/atom-neon-cursor)
- [Neon Selection](https://github.com/muchweb/atom-neon-selection)
- [Neon Brackets (Fancy Bracket Matcher)](https://github.com/Evpok/fancy-bracket-matcher)
